import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>{"Amirrul Kasmirhan's Portfolio"}</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="h-screen grid md:grid-cols-2 sm:grid-cols-1 gap-4">
				<div className="flex flex-col items-center justify-center py-16">
					<div className="flex flex-col w-4/5">
						<h2 className="font-bold text-5xl">HI THERE!</h2>
						<h1 className="font-bold text-7xl">
							{"I'M"} <span className="text-emerald-300">AMIRRUL</span>
						</h1>
						<div className="flex">
							<div className="bg-emerald-300 py-1 px-3 mt-4">
								<h6 className="font-bold">
									SOFTWARE DEVELOPER 💻 / <span className="line-through">MODEL 🍑</span>
								</h6>
							</div>
						</div>
						<div className="mt-8">
							<p>
								{
									"I'm a software developer and a self-proclaimed model. I'm currently working as a software developer at Recap Sdn Bhd. Drop me a text if you want to talk to me about anything."
								}
							</p>
						</div>
						<div className="mt-8">
							<button className="bg-emerald-300 hover:bg-emerald-500 text-white font-bold px-5 py-3 rounded-full transition-all">MORE ABOUT ME</button>
						</div>
					</div>
				</div>
				<div className="flex items-center justify-center relative bg-emerald-100">
					<div className="sm:max-w-sm md:max-w-lg w-full">
						<Image src="/images/sexy-amirrul-2.png" alt="Amirrul Kasmirhan" height={1088} width={713} layout="responsive" />
					</div>
				</div>
			</div>
		</>
	);
};

export default Home;
