import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
	const navItems = [
		{
			label: "home",
			href: "#home",
		},
		{
			label: "about me",
			href: "#about",
		},
		{
			label: "resume",
			href: "#resume",
		},
		{
			label: "portfolio",
			href: "#portfolio",
		},
		{
			label: "testimonials",
			href: "#testimonials",
		},
		{
			label: "contact",
			href: "#contact",
		},
	];
	return (
		<>
			<Head>
				<title>{"Amirrul Kasmirhan's Portfolio"}</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* home */}
			<div className="md:h-screen grid md:grid-cols-2 grid-cols-1 gap-4" id="home">
				<div className="flex flex-col items-center justify-center py-16 text-center md:text-left">
					<div className="flex flex-col md:w-4/5 mx-4 md:mx-0">
						<h2 className="font-bold md:text-5xl text-4xl">HI THERE!</h2>
						<h1 className="font-bold md:text-7xl text-5xl">
							{"I'M"} <span className="text-emerald-300">AMIRRUL</span>
						</h1>
						<div className="flex justify-center md:justify-start">
							<div className="bg-emerald-300 py-1 px-3 mt-4">
								<h6 className="font-bold md:text-md text-sm">
									SOFTWARE DEVELOPER 💻 / <span className="line-through">MODEL 🍑</span>
								</h6>
							</div>
						</div>
						<div className="mt-8">
							<p>
								{
									"I'm a software developer and a self-proclaimed model. I'm currently working as a software developer at Recap Sdn Bhd. Drop me a text if you want to talk to me about anything."
								}
							</p>
						</div>
						<div className="mt-8">
							<button className="bg-emerald-300 hover:bg-emerald-500 text-white font-bold px-5 py-3 rounded-full transition-all">MORE ABOUT ME</button>
						</div>
					</div>
				</div>
				<div className="flex items-center justify-center relative bg-emerald-100">
					<div className="max-w-sm md:max-w-lg w-full">
						<Image src="/images/sexy-amirrul-2.png" alt="Amirrul Kasmirhan" height={1088} width={713} layout="responsive" />
					</div>
				</div>
			</div>
			{/* about me */}
			<div className="flex h-screen bg-gray-100">
				{/* left drawer navigator */}
				<nav className="bg-emerald-100 h-screen top-0 left-0 flex-col hidden md:flex">
					<div className="flex items-center justify-center relative bg-emerald-100">
						<div className="max-w-sm md:max-w-lg w-full mx-8">
							<Image src="/images/sexy-amirrul-2.png" alt="Amirrul Kasmirhan" height={1088} width={713} layout="responsive" />
						</div>
					</div>
					<div className="grow flex items-center justify-center px-16">
						<ul className="flex items-center justify-center flex-col">
							<div className="w-2 h-2 rounded-full bg-black" />
							<div className="border-dashed border-black h-4 border-r" />
							{navItems.map((item) => (
								<NavItem key={item.href} {...item} />
							))}
							<div className="w-2 h-2 rounded-full bg-black" />
						</ul>
					</div>
				</nav>
				<div className="container grow">
					<div className="flex items-center justify-center">
						<div className="border-dashed border w-full flex justify-center items-center py-4 border-gray-400 my-16 mx-4">
							<h2 className="font-bold text-4xl md:text-8xl">ABOUT ME</h2>
						</div>
					</div>
					<div className="md:ml-4 text-center md:text-left">
						<h4 className="text-2xl md:text-4xl">
							{"I'm"} <span className="font-bold">Amirrul Kasmirhan,</span> Fullstack / Application Developer
						</h4>
						<p className="my-8">
							Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus molestias, autem, aliquid dicta, accusantium voluptates quis modi natus
							perspiciatis pariatur vero provident veritatis dolorum amet aut qui? Neque, illo nostrum. Lorem ipsum, dolor sit amet consectetur adipisicing
							elit. Odio neque, maiores blanditiis consequatur optio perferendis nulla eum, voluptate praesentium nihil earum similique error in? Veritatis
							obcaecati ea ut earum quasi.
						</p>
						<div className="grid grid-cols-1 md:grid-cols-5">
							<div className="col-span-3">
								<div className="bg-black p-8">
									<div className="grid grid-cols-1 md:grid-cols-2">
										<div className="bg-black flex justify-center items-center p-8 flex-col border-r-0 md:border-r border-b border-dashed">
											<h2 className="text-emerald-300 font-bold text-6xl">1+</h2>
											<p className="text-white uppercase font-bold mt-2">Years Experience</p>
										</div>
										<div className="bg-black flex justify-center items-center p-8 flex-col border-b border-dashed">
											<h2 className="text-emerald-300 font-bold text-6xl">10+</h2>
											<p className="text-white uppercase font-bold mt-2">Projects done</p>
										</div>
										<div className="bg-black flex justify-center items-center p-8 flex-col border-r-0 md:border-r md:border-b-0 border-b border-dashed">
											<h2 className="text-emerald-300 font-bold text-6xl">10+</h2>
											<p className="text-white uppercase font-bold mt-2">Happy Clients</p>
										</div>
										<div className="bg-black flex justify-center items-center p-8 flex-col">
											<h2 className="text-emerald-300 font-bold text-6xl">0</h2>
											<p className="text-white uppercase font-bold mt-2">Followers</p>
										</div>
									</div>
								</div>
							</div>
							<div className="col-span-2 my-8 md:my-0 md:ml-8">
								<h4 className="text-4xl font-bold mb-8">What I Do?</h4>
								<div className="grid grid-cols-1 md:grid-cols-4 justify-center my-2">
									<div className="flex justify-center my-4 md:mr-4">
										<div className="w-32">
											<Image src="/images/web-dev.svg" width={1170} height={911} alt="web development logo" />
										</div>
									</div>
									<div className="flex flex-col md:col-span-3">
										<h6 className="uppercase font-extrabold text-lg mb-2">Fullstack developer</h6>
										<p className="text-sm">
											Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, laborum impedit minima accusantium aperiam quam atque tempora
											obcaecati dicta neque consequuntur eaque sint ea officiis enim a. Praesentium, sunt suscipit!
										</p>
									</div>
								</div>
								<div className="grid grid-cols-1 md:grid-cols-4 justify-center my-2">
									<div className="flex justify-center my-4 md:mr-4">
										<div className="w-32">
											<Image src="/images/mobile-dev.svg" width={1170} height={911} alt="application development logo"/>
										</div>
									</div>
									<div className="flex flex-col md:col-span-3">
										<h6 className="uppercase font-extrabold text-lg mb-2">Application developer</h6>
										<p className="text-sm">
											Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, laborum impedit minima accusantium aperiam quam atque tempora
											obcaecati dicta neque consequuntur eaque sint ea officiis enim a. Praesentium, sunt suscipit!
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

const NavItem = ({ label, href }: { label: string; href: string }) => {
	return (
		<>
			<li className="py-1">
				<a href={href} className="text-lg uppercase font-black hover:text-emerald-400 transition-all">
					<h3>{label}</h3>
				</a>
			</li>
			<div className="border-dashed border-black h-4 border-r" />
		</>
	);
};

export default Home;
